# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
target 'FishX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FishX

    pod 'FMDB', '~> 2.7.2'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'AwesomeMenu', '~> 1.0.0'
    pod 'SDWebImage', '~> 4.1.2'
  
end
